services:
  postgresInventory:
    image: postgres:15
    container_name: postgresInventory
    environment:
      POSTGRES_USER: Inventory
      POSTGRES_PASSWORD: Inventory.ps
      POSTGRES_DB: Inventory_db
    ports:
      - "5434:5432"
    volumes:
      - postgresInventory:/var/lib/postgresql/dataInventory

volumes:
  postgresInventory:
